/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.beru.ServerController;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.text.Font;
import javafx.stage.Stage;
import org.beru.ServerController.Model.Dirs;

public class App extends Application {

    static {
        try {
            Font.loadFont(new FileInputStream(new File("B:\\Resources\\Fonts\\escape-artist-font\\EscapeArtistBold-EaaBz.otf")), 10);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }

    public static Stage stage;

    @Override
    public void start(Stage stage) throws Exception {
        new Dirs();
        
        App.stage = stage;
        Parent root = FXMLLoader.load(getClass().getResource("/Views/Application.fxml"));
        Scene scene = new Scene(root);
        scene.getStylesheets().add(getClass().getResource("/Styles/style.css").toExternalForm());

        stage.setTitle("Remote Connection");
        stage.setAlwaysOnTop(true);
        stage.setScene(scene);
        stage.setFullScreen(true);
        stage.show();

    }

    public static void main(String[] args) {
        launch(args);
    }

}
